### ISSUE TITLE
Problems with CMakeLists.txt on windows,

### ISSUE THREAD

**Issue by fabianbuettner** [i-rinat/nginx-cmake#1]
Hi,
the following platform detection code is causing problems on windows.
```
if (NGX_PLATFORM STREQUAL "")
    message(STATUS "ngx: checking for OS")
    execute_process(COMMAND uname -s
                    OUTPUT_VARIABLE NGX_SYSTEM
                    ERROR_QUIET
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND uname -r
                    OUTPUT_VARIABLE NGX_RELEASE
                    ERROR_QUIET
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND uname -s
                    OUTPUT_VARIABLE NGX_MACHINE
                    ERROR_QUIET
                    OUTPUT_STRIP_TRAILING_WHITESPACE)

    message(STATUS "ngx:  + ${NGX_SYSTEM} ${NGX_RELEASE} ${NGX_MACHINE}")

    set(NGX_PLATFORM "${NGX_SYSTEM}:${NGX_RELEASE}:${NGX_MACHINE}")

else()
    message(STATUS "ngx: building for ${NGX_PLATFORM}")
endif()
```
and later:
```
if ("${NGX_RELEASE}" VERSION_LESS "2.5.60")
    ngx_nohave("NGX_HAVE_POSIX_FADVISE")
endif()
```

Any idea on how to fix this?

regards,
Fabian

**Comment by i-rinat** [comment]
Hi.

I've done rewriting while targeting Linux [1], so even with `ngx_nohave()` implemented, it most probably won't work on Windows. Adding support for other OSes would cause a significant changes and a need for a lot more testing than I could perform. Also, those changes won't be final, since various Nginx versions have different set of features.

Since then I realized, that with a handwritten CMakeLists.txt I'm tied to a Nginx version 1.11.6, and won't be able to easily change it without pain.

I'm using the [tracing script](https://github.com/i-rinat/nginx-cmake/tree/master/tracing-script) now: it reuses native Nginx build scripts to generate CMakeLists.txt. And I think, it should work on other OSes too, including Windows, if there are shell scripts, Python and GCC available. You are using something like mingw or Cygwin, right?


[1] there is a comment stating that, in the first two lines of CMakeLists.txt

**Comment by i-rinat** [comment]
Added a bit more information to README file: e3c067525eba7be941dc05af4cdf50fbe68b862e

**Comment by fabianbuettner** [comment]
Hi @i-rinat,

I had this issue while cross compiling on Windows for a ARM Linux machine.

I see. So you are probably not going to do a rewrite for newer versions?
Not sure, if i want to implement a python script in my build system.

regards,
Fabian

**Comment by i-rinat** [comment]
> So you are probably not going to do a rewrite for newer versions?

Definitely not. That takes too long. And after some time passed I'm afraid to touch the code I written, it's too fragile.

> Not sure, if i want to implement a python script in my build system.

Perhaps, I didn't state it clear, but that script is not something you should run every time you build Nginx. It's enough to run it offline once per Nginx version change, which is not often. You call it, take generated CMakeLists.txt, make changes, if required, and put that CMakeLists.txt into repository. At least, that's how I use it.
